//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public int ShopID { get; set; }
        public string ShopName { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public string Product { get; set; }
    }
}
